### PR TITLE
Updated privacy policy to ttk2's pdf

### PR DESCRIPTION
**Pull request by ghost**
Just updated the wording of the privacy policy page to match the pdf ttk2 sent me

### CODE REVIEW

**Comment by ttk2** [comment]
and now we wait for it to bake.

**Comment by ghost** [comment]
Well we need to update the github pages for the site I think. @drjawa did it last time.

**Comment by ghost** [comment]
I'll update it tomorrow

**Comment by ghost** [comment]
Sweet
Thanks Dr Jawa!

**Comment by ghost** [comment]
I'll make TOS and PP compliance mandatory on the forum after that.

**Pull request merged**
