### PR TITLE
Added privacy policy and terms of service

### PR DESCRIPTION
**Pull request by ghost**
The privacy policy and terms of service pages have been created and added to the link list

### CODE REVIEW

**Comment by ttk2** [comment]
much better.

**Comment by ttk2** [comment]
where do I find the new page? also we should probably remove the online players text since we removed the online players stuff.

**Comment by ghost** [comment]
The new pages are under termsofservice.html and privacypolicy.html

I added them to the link list. They should be there...

**Comment by ttk2** [comment]
so its supposed to show up in the top links? 

Oh wait I forget it takes forever for them to refresh this.

**Comment by ghost** [comment]
Have they showed up yet?

**Comment by erocs** [comment]
You need to push the changes into the gh-pages branch.
https://help.github.com/articles/creating-project-pages-manually/

It looks like master and gh-pages were out of sync even before your change.

**Comment by ghost** [comment]
Sheeet

I'll make a pull request

**Comment by ttk2** [comment]
ok then, so this giant comment is just updating ghpages?

**Comment by ghost** [comment]
Yes

**Pull request merged**
