### PR TITLE
Updating the github pages

### PR DESCRIPTION
**Pull request by ghost**
If we can merge this pull request then the civcraft site will finally show the Terms of Service and Privacy Policy.

Citation: https://github.com/Civcraft/civcraftsite/pull/15#issuecomment-127409838

### CODE REVIEW

**Comment by ttk2** [comment]
this is not a valid pull, moreover it seriously needs to be squashed, gitfu is off here somehow.

**Comment by ghost** [comment]
You don't need to do this. See the page on github pages and jekyll.
Just need to:
1. Clone master repo
2. Follow github page instructions on using jekyll to build the
   website (This will generate a _site folder with updated assets)
3. Clone origin:gh-pages.
4. Overwrite gh-pages repo contents with contents of _site from master

Something along those lines. I'll have some time tomorrow to do if no
one beats me to it.

Just be sure to preview whatever you are about to merge to make sure
it was done properly.

**Comment by ghost** [comment]
Unfortunately I have little to no time with the moving. I would be grateful
if you did that Jawa.

**Comment by ghost** [comment]
> Error reading file /home/drjawa/civcraftsite/termsofservice.html: invalid byte sequence in UTF-8 
> Error reading file /home/drjawa/civcraftsite/privacypolicy.html: invalid byte sequence in UTF-8 

When I try to generate the site. Any ideas? Maybe I am doing something wrong like using an old ruby version.

**Comment by erocs** [comment]
He must have used some unicode characters and didn't save it in utf-8. Try
opening it and re-saving it as utf-8.

**Comment by ghost** [comment]
Hmm. I didn't think of that. I'll try to correct that tonight after the
movers take all my stuff.

**Comment by ghost** [comment]
Converted them to UTF-8 on my laptop. That's what I get for using Windows.

**Comment by ghost** [comment]
Update the master repo and I'll update it for gh-pages

**Comment by ghost** [comment]
https://github.com/Civcraft/civcraftsite/pull/17
Done. It should work now.

**Comment by ghost** [comment]
Ok see https://i.imgur.com/mJik6pw.png

I think we have too many links in this sidebar thing. They don't need immediate attention either so maybe instead throw the links within the main page. "See our Privacy policy and terms of use" yadayada

**Comment by ghost** [comment]
I think if we make the link box wider then it'll accommodate them

**Comment by ttk2** [comment]
do we really want it to be at the top? I would want it in a footnote at the bottom and we can link people to it.

**Comment by ghost** [comment]
Yeah that's what I had in mind. At bottom of all pages would be a footnote for TOS and PP.

**Comment by ttk2** [comment]
bump, how is this going bob?

**Comment by ghost** [comment]
I can make those changes after 5pm central time today when I get internet
access for my laptop.

**Comment by ttk2** [comment]
cool, it would be great to see it done some time this weekend, no major
rush.

**Comment by ghost** [comment]
I'll work on this tomorrow.

**Comment by ghost** [comment]
Done: https://github.com/Civcraft/civcraftsite/pull/18

Sorry it took so long. I didn't have internet at many hotels on the road, and I just got internet at my house.

**Comment by ttk2** [comment]
no problem, thanks!

**Comment by ghost** [comment]
Closing this pull since it is not needed.

**Comment by ghost** [comment]
@bobpndrgn Your latest changes are now live on civcraft.co

Looks great, you did very well.

**Pull request closed without merging**
